import Link from "next/link";
import { bulkLeadAction } from "@/app/lead-actions";
import { Badge, EmptyState } from "@/components/ui";
import { leadStatusLabels, type LeadStatus } from "@/features/leads/bulk-actions";
import type { listLeads } from "@/features/leads/queries";

type LeadItem = ReturnType<typeof listLeads>["items"][number];

export function LeadTable({ leads, campaignId, emptyTitle = "Nenhum lead encontrado" }: { leads: LeadItem[]; campaignId?: string; emptyTitle?: string }) {
  if (!leads.length) return <EmptyState title={emptyTitle} description="Ajuste os filtros ou execute uma campanha para preencher esta lista." />;
  return <form action={bulkLeadAction}><input type="hidden" name="campaignId" value={campaignId ?? ""} /><div className="bulk-bar"><span>{leads.length} lead(s) nesta página</span><button name="action" value="shortlist" className="button">Adicionar à shortlist</button><button name="action" value="generate_outreach" className="button">Gerar abordagem</button><button name="action" value="dry_run" className="button">Dry-run email</button><button name="action" value="send_email" className="button">Enviar email</button><button name="action" value="suppress" className="button danger">Não contatar</button></div><div className="table-wrap"><table className="leads-table"><thead><tr><th><span className="sr-only">Selecionar</span></th><th>Empresa</th><th>Score</th><th>Conf.</th><th>Segmento / local</th><th>Oportunidade</th><th>Contato</th><th>Fonte</th><th>Status</th><th>Data</th></tr></thead><tbody>{leads.map((lead) => <tr key={lead.id}><td><input type="checkbox" name="leadIds" value={lead.id} aria-label={`Selecionar ${lead.companyName}`} /></td><td><Link className="lead-name" href={`/leads/${lead.id}`}>{lead.companyName}</Link>{lead.website && <small>{new URL(lead.website).hostname}</small>}</td><td><strong className="score-number">{lead.score ?? "—"}</strong></td><td>{lead.confidence != null ? `${lead.confidence}%` : "—"}</td><td>{lead.industry ?? "Não detectado"}<small>{lead.location || "Local não detectado"}</small></td><td className="opportunity-cell">{lead.opportunity ?? "Não analisada"}</td><td>{lead.email ?? lead.phone ?? lead.instagram ?? "Não detectado"}</td><td>{lead.sources.join(", ")}</td><td><Badge tone={["qualified","shortlisted","draft_ready"].includes(lead.status) ? "success" : "neutral"}>{leadStatusLabels[lead.status as LeadStatus] ?? lead.status}</Badge></td><td>{new Intl.DateTimeFormat("pt-BR", { dateStyle: "short" }).format(new Date(lead.createdAt))}</td></tr>)}</tbody></table></div></form>;
}
