import { db } from "@/db/client";
import { listCampaigns } from "@/features/campaigns/actions";
import { listLeads } from "@/features/leads/queries";
import { LeadTable } from "@/components/lead-table";
import { Input, PageHeader } from "@/components/ui";

export const dynamic = "force-dynamic";

export default async function LeadsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const query = await searchParams; const value = (name: string) => typeof query[name] === "string" ? query[name] as string : "";
  const campaignId = value("campaign"); const minimumScore = value("score"); const campaigns = listCampaigns(db);
  const result = listLeads(db, { campaignId: campaignId || undefined, minimumScore: minimumScore ? Number(minimumScore) : undefined, minimumConfidence: value("confidence") ? Number(value("confidence")) : undefined, search: value("q") || undefined, status: value("status") || undefined, location: value("location") || undefined, industry: value("industry") || undefined, hasEmail: value("email") === "yes" || undefined, hasPhone: value("phone") === "yes" || undefined, hasInstagram: value("instagram") === "yes" || undefined, hasWebsite: value("website") === "yes" || undefined, source: value("source") || undefined, signal: value("signal") || undefined }, { field: (value("sort") || "score") as "score" | "confidence" | "date" | "name", direction: "desc" });
  return <><PageHeader eyebrow="CRM" title="Leads" description={`${result.total} empresas encontradas. Filtre, compare e escolha quem merece atenção agora.`} />
    <form className="filter-bar"><Input name="q" defaultValue={value("q")} placeholder="Buscar empresa ou contexto" /><select className="input" name="campaign" defaultValue={campaignId}><option value="">Todas as campanhas</option>{campaigns.map((campaign) => <option value={campaign.id} key={campaign.id}>{campaign.name}</option>)}</select><Input name="score" type="number" min="0" max="100" defaultValue={minimumScore} placeholder="Score mínimo" /><Input name="confidence" type="number" min="0" max="100" defaultValue={value("confidence")} placeholder="Confiança mín." /><Input name="location" defaultValue={value("location")} placeholder="Localização" /><Input name="industry" defaultValue={value("industry")} placeholder="Segmento" /><Input name="signal" defaultValue={value("signal")} placeholder="Oportunidade / sinal" /><select className="input" name="source" defaultValue={value("source")}><option value="">Todas as fontes</option><option value="csv">CSV</option><option value="seed_urls">URLs iniciais</option><option value="overpass">OpenStreetMap</option><option value="google_places">Google Places</option></select><select className="input" name="status" defaultValue={value("status")}><option value="">Todos os status</option><option value="qualified">Qualificado</option><option value="shortlisted">Shortlist</option><option value="contacted">Contatado</option><option value="replied">Respondeu</option><option value="won">Ganho</option></select><select className="input" name="email" defaultValue={value("email")}><option value="">Email: todos</option><option value="yes">Possui email</option></select><select className="input" name="phone" defaultValue={value("phone")}><option value="">Telefone: todos</option><option value="yes">Possui telefone</option></select><select className="input" name="instagram" defaultValue={value("instagram")}><option value="">Instagram: todos</option><option value="yes">Possui Instagram</option></select><select className="input" name="website" defaultValue={value("website")}><option value="">Website: todos</option><option value="yes">Possui website</option></select><select className="input" name="sort" defaultValue={value("sort") || "score"}><option value="score">Ordenar: score</option><option value="confidence">Confiança</option><option value="date">Data</option><option value="name">Nome</option></select><button className="button" type="submit">Aplicar filtros</button></form>
    <LeadTable leads={result.items} campaignId={campaignId || campaigns[0]?.id} />
  </>;
}
